from typing import Protocol

from src.domain.entities import TicketEventEntity


class RoomRepo(Protocol):
    async def create(self, room_id: str, fingerprint: str) -> None: ...
    async def close(self, room_id: str) -> None: ...
    async def increment_tickets(self, room_id: str) -> None: ...


class TicketRepo(Protocol):
    async def create_event(
        self, room_id: str, queue_label: str, ticket_num: str, fingerprint: str
    ) -> None: ...
    async def mark_called(self, room_id: str, queue_label: str, ticket_num: str) -> None: ...
    async def mark_completed(self, room_id: str, queue_label: str, ticket_num: str) -> None: ...
    async def get_events(self, room_id: str) -> list[TicketEventEntity]: ...


class QueueRepo(Protocol):
    async def room_exists(self, room_id: str) -> bool: ...
    async def get_queues(self, room_id: str) -> list[str]: ...
    async def init_queue(self, room_id: str, label: str) -> None: ...
    async def add_queue(self, room_id: str, label: str) -> bool: ...
    async def remove_queue(self, room_id: str, label: str) -> bool: ...
    async def pick_shortest_queue(self, room_id: str) -> str: ...
    async def get_state(self, room_id: str, user_id: str) -> dict: ...
    async def close_room_keys(self, room_id: str) -> None: ...
    async def get_owner(self, room_id: str) -> str | None: ...
    async def set_owner(self, room_id: str, fingerprint: str) -> None: ...
    async def get_user_queue(self, room_id: str, fingerprint: str) -> str | None: ...
    async def take_ticket(self, room_id: str, label: str, fingerprint: str) -> tuple[str, int]: ...
    async def call_next(self, room_id: str, label: str) -> tuple[str, str, str]: ...
    async def complete_serving(self, room_id: str, label: str) -> tuple[str, str, str, int]: ...
    async def leave_queue(self, room_id: str, fingerprint: str) -> None: ...
    async def update_avg_serve(self, room_id: str, serve_seconds: int) -> None: ...
    async def get_existing_ticket(
        self, room_id: str, fingerprint: str
    ) -> tuple[str, str, int | None] | None: ...


class WebSocketBroadcaster(Protocol):
    async def broadcast(self, room_id: str, payload: dict) -> None: ...
    async def connect(self, room_id: str, websocket: object, user_id: str) -> None: ...
    def disconnect(self, room_id: str, websocket: object) -> None: ...
